name: build pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ deployment ]
  pull_request:
    branches: [ development ]
jobs:
  build:
    runs-on: self-hosted

    steps:
    #- name: Set up Docker Buildx
     # uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 
          repository: Dinahalem/Bitot_test
                     
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: Dinahalem/bitot_test
          push: true
          tags: dina2022/botit
      
 
  
  deploy_to_docker:
    name: Push to EC2 Instance
    runs-on: LAPTOP-DVVKMAF8

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Deploy to Server1
        #uses: Dinahalem/Bitot_test@deployment
        env: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
        run: |
           #docker stop new_app
           #docker rm new_app
           docker run -d -p 127.0.0.1:5000 --name new_app dina2022/botit 
